name: Deploy on Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/simple-flask-app:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/simple-flask-app:latest

    - name: Deploy to remote server
      uses: appleboy/ssh-action@v0.5.3
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/simple-flask-app:latest
          docker stop simple-flask-app || true
          docker rm simple-flask-app || true
          docker run -d -p 5000:5000 --name simple-flask-app ${{ secrets.DOCKER_USERNAME }}/simple-flask-app:latest
